### PR TITLE
Fix/ignore button via js

### LINKED ISSUE #24: Don't move to the top of page when clicking "Ignore" button on a long page

### PR DESCRIPTION
**Pull request by heggern**
Added lightweight javascript (no framework other then already included axios) to handle request for both "Ignore" and "Un-Ignore", removing item from the list and prevents the "jump to top" effect.

(closes #24 )

### CODE REVIEW

File: app/Http/Controllers/IgnoreProjectController.php [hunk 1]
```diff
@@ -8,8 +8,13 @@ class IgnoreProjectController extends Controller
 {
     public function __invoke(Project $project)
     {
-        $project->update(['ignored' => true]);
-
+				$project->update(['ignored' => true]);
+				
+				if (request()->wantsJson()) {
```
Comment (marcusmoore) [inline app/Http/Controllers/IgnoreProjectController.php:13]: I believe we will always be returning json so we can remove this conditional.

File: app/Http/Controllers/UnIgnoreProjectController.php [hunk 2]
```diff
@@ -10,6 +10,12 @@ public function __invoke(Project $project)
     {
         $project->update(['ignored' => false]);
 
+				if (request()->wantsJson()) {
```
Comment (marcusmoore) [inline app/Http/Controllers/UnIgnoreProjectController.php:13]: I believe we will always be returning json so we can remove this conditional.

File: app/Http/Controllers/IgnoreProjectController.php [hunk 3]
```diff
@@ -8,8 +8,13 @@ class IgnoreProjectController extends Controller
...
+					return response()->json([
+						'success' => true
+					], 200);
+				}
```
Comment (marcusmoore) [inline app/Http/Controllers/IgnoreProjectController.php:17]: Instead of returning `'success' => true`, let's just return the positive status code.

`response()->json([], 200)` should do it I think.

File: app/Http/Controllers/UnIgnoreProjectController.php [hunk 4]
```diff
@@ -10,6 +10,12 @@ public function __invoke(Project $project)
...
+					return response()->json([
+						'success' => true
+					], 200);
```
Comment (marcusmoore) [inline app/Http/Controllers/UnIgnoreProjectController.php:16]: Instead of returning `'success' => true`, let's just return the positive status code.

`response()->json([], 200)` should do it I think.

File: resources/js/app.js [hunk 5]
```diff
@@ -7,16 +7,35 @@
...
 
-Vue.component('example-component', require('./components/ExampleComponent.vue'));
+// Vue.component('example-component', require('./components/ExampleComponent.vue'));
 
-const app = new Vue({
-    el: '#app'
-});
+// const app = new Vue({
+//     el: '#app'
+// });
```
Comment (marcusmoore) [inline resources/js/app.js:22]: Thank you for commenting this out. We're not using it in the app so it's just increasing the bundle size.

File: resources/js/app.js [hunk 6]
```diff
@@ -7,16 +7,35 @@
...
+			document.getElementById('project_' + id).style.display = 'none';
+			counterElement.innerHTML = (count-1);
+		}
+		else {
+			alert('Sorry, something went wrong!');
+		}
+	});
+}
+
+global.ignoreProject = ignoreProject;
```
Comment (marcusmoore) [inline resources/js/app.js:41]: Please re-add the newline at the bottom of the file.

File: resources/views/ignored.blade.php [hunk 7]
```diff
@@ -3,6 +3,9 @@
 @section('content')
 <div class="bg-gray-100 font-sans relative z-0">
     <div class="max-w-6xl mx-auto pt-8">
+				<p class="mb-6 text-black-lighter">
+            Showing <span id="projectCounter">{{ $projects->count() }}</span> ignored projects and packages
```
Comment (marcusmoore) [inline resources/views/ignored.blade.php:7]: Nitpicky but can you snake_case this id like you did with `id="project_{{ $project->id }}"` below please?

File: resources/views/ignored.blade.php [hunk 8]
```diff
@@ -12,19 +15,15 @@
...
                             </a>
                         </li>
 
                         <li class="w-1/2 text-right">
-                            <form action="{{ route('project.unignore', $project) }}" method="POST">
-                                @method('PATCH')
-                                @csrf
-                                <input type="submit" value="Un-Ignore" class="bg-indigo-600 hover:bg-indigo-500 text-white px-3 py-1 rounded cursor-pointer">
-                            </form>
+														<button onClick="ignoreProject({{$project->id}}, false);" type="button" class="bg-indigo-600 hover:bg-indigo-500 text-white px-3 py-1 rounded cursor-pointer">Un-Ignore</button>
```
Comment (marcusmoore) [inline resources/views/ignored.blade.php:26]: Not so important but instead of passing an `ignore = false` flag here, can make a dedicated function called `unignoreProject(projectId)`? That would allow developers browsing the codebase  to not to have to think about what passing `false` here does.

I think keeping `ignoreProject()`'s signature the same and having `unignoreProject()` just call it with the boolean would good.

File: resources/views/welcome.blade.php [hunk 9]
```diff
@@ -11,7 +11,7 @@
 <div class="bg-gray-100 font-sans relative z-0">
     <div class="max-w-6xl mx-auto pt-8">
         <p class="mb-6 text-black-lighter">
-            Showing versions for {{ $projects->count() }} active projects and packages
+            Showing versions for <span id="projectCounter">{{ $projects->count() }}</span> active projects and packages
```
Comment (marcusmoore) [inline resources/views/welcome.blade.php:14]: Nitpicky but can you snake_case this id like you did with `id="project_{{ $project->id }}"` below please?

**Review by marcusmoore — CHANGES_REQUESTED** [review]
Thanks @heggern! I like your simple Javascript approach. It's been a while since I've used `document.getElementById` and `innerHTML` 😄 .

Can you take a look at the requests I've made and update please? Feel free to ask questions if needed.

**Also**: can you switch your changes to use spaces instead of tabs (for consistency with the rest of the codebase) and double-check how items are lined up? Some code is indented further than the surrounding code:

image

image

File: app/Http/Controllers/IgnoreProjectController.php (hunk 1 above)
Comment (heggern) [reply app/Http/Controllers/IgnoreProjectController.php]: Fixed with latest commit

File: app/Http/Controllers/UnIgnoreProjectController.php (hunk 2 above)
Comment (heggern) [reply app/Http/Controllers/UnIgnoreProjectController.php]: Fixed with latest commit

File: app/Http/Controllers/IgnoreProjectController.php (hunk 3 above)
Comment (heggern) [reply app/Http/Controllers/IgnoreProjectController.php]: Fixed

File: resources/js/app.js (hunk 6 above)
Comment (heggern) [reply resources/js/app.js]: Not quite sure if I understand what you mean here?

File: resources/views/ignored.blade.php (hunk 7 above)
Comment (heggern) [reply resources/views/ignored.blade.php]: Sure thing

File: resources/views/ignored.blade.php (hunk 8 above)
Comment (heggern) [reply resources/views/ignored.blade.php]: Sure, make sense. Implemented.

File: resources/views/welcome.blade.php (hunk 9 above)
Comment (heggern) [reply resources/views/welcome.blade.php]: Snake it is :)

File: resources/js/app.js (hunk 6 above)
Comment (heggern) [reply resources/js/app.js]: If you're refering to the new unignoreProject function, thats what I did

**Comment by heggern** [comment]
I've submitted the requested changes, and tried to format the tabs/spaces thing. 

My formatter settings in VS Code try to change almost all lines of the files, so I had to turn the autoformat off.

And yes, many years since I wrote some basic js like this, but when you don't need a framework, why both? :)

File: resources/js/app.js (hunk 5 above)
Comment (marcusmoore) [reply resources/js/app.js:22]: Removing the unused javascript! 👍 
image

File: resources/js/app.js (hunk 6 above)
Comment (marcusmoore) [reply resources/js/app.js]: There was a newline at the end of this file but it's not a big deal 😄 

image

**Review by marcusmoore — APPROVED** [review]
Awesome! Thanks @heggern 😄
